config/routes.rb
Rails.application.routes.draw do
  root 'inquirys#index'
  get 'inquirys/menu'
  get 'inquirys/appointment'
  get 'inquirys/access'
  get 'inquirys/menu_display'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/inquirys_controller.rb
class InquirysController < ApplicationController
  def index  
  end

  def menu
  end

  def appointment
  end

  def access
  end

  def menu_display
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquirys_helper.rb
module InquirysHelper
end

app/views/inquirys/access.html.erb
<%= render "shared/header" %>

<div class="access">
  <div class="title">
    <div class="title-up">information / access</div>
    <div class="title-middle">-</div>
    <div class="title-down">サロン案内／アクセス</div>
  </div>

  <div class="home-image">
    <%= image_tag asset_path("este_room6.jpg"), class:"home" %>
  </div>

  <div class="access-adress">
    <div class="name">【　HEALTH & BEAUTY  TORa　】</div>
    <div class="adress">〒381-2223 長野県長野市里島27-2<br> タウンコートいずみ B102号室</div>
    <div class="phone-number">TEL 090-3408-3514</div>
    <div class="time">営業時間 10：00 〜 17：00 </div>
    完全予約制
  </div>

  <div class="map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3203.8945784601055!2d138.15274949999994!3d36.580758200000005!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x601d8384790b477f%3A0x10a1138aa568a0b2!2z44CSMzgxLTIyMjMg6ZW36YeO55yM6ZW36YeO5biC6YeM5bO277yS77yX4oiS77ySIOOCv-OCpuODs-OCs-ODvOODiCDjgYTjgZrjgb8gQQ!5e0!3m2!1sja!2sjp!4v1690082679566!5m2!1sja!2sjp" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
  </div>


</div>


<%= render "shared/footer" %>

app/views/inquirys/appointment.html.erb
<%= render "shared/header" %>

<div class="appointment">
ご予約
</div>

<div class="slider-wrapper">
   <div class="slide-container">
      <div class="slide-wrapper">
         <%= image_tag "tiikawa1.png", class:"slide" %>
         <%= image_tag "tiikawa.jpeg", class:"slide" %>
         <%= image_tag "tiikawa2.png", class:"slide" %>
      </div>
      <div class="slide-wrapper">
         <%= image_tag "tiikawa1.png", class:"slide" %>
         <%= image_tag "tiikawa.jpeg", class:"slide" %>
         <%= image_tag "tiikawa2.png", class:"slide" %>
      </div>
      <div class="slide-wrapper">
         <%= image_tag "tiikawa1.png", class:"slide" %>
         <%= image_tag "tiikawa.jpeg", class:"slide" %>
         <%= image_tag "tiikawa2.png", class:"slide" %>
      </div>
   </div>
   <div class="btns-wrapper">
      <button id="stopBtn" class="slider-btn">STOP</button>
      <button id="startBtn" class="slider-btn">START</button>
   </div>
</div>

<%= render "shared/footer" %>

app/views/inquirys/index.html.erb
<div id="bar"></div>
<%= render "shared/header" %>
<div class='main-page'>
  <!-- トップ画像を表示 -->
<div id="photo">
    <%= image_tag "este_room5.jpg", class:"image" %>
    <%= image_tag "este_room1.jpg", class:"image" %>
    <%= image_tag "este_room2.jpg", class:"image" %>
</div>

<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script type="text/javascript">
$(function(){
    const setImg = '#photo';
    const fadeSpeed = 1600;
    const switchDelay = 5000;

    $(setImg).children('img').css({opacity:'0'});
    $(setImg + ' img:first').stop().animate({opacity:'1',zIndex:'20'},fadeSpeed);

    setInterval(function(){
        $(setImg + ' :first-child').animate({opacity:'0'},fadeSpeed).next('img').animate({opacity:'1'},fadeSpeed).end().appendTo(setImg);
    },switchDelay);
});
</script>

<body>
  <div class='contents'>

    <!-- メニュー画面を表示 -->
    <div class="menu-content">
        <div class="line"></div>
      <div class="title">
        <div class="title-up">menu</div>
        <div class="title-middle">-</div>
        <div class="title-down">【 それぞれのお体に合わせた最適なケアのご提案 】</div>
      </div>
      <%= image_tag "este_menu.jpg", class: "este1-image" %>
        <p class="menu_title_middle">TORa オリジナルメニューをはじめ、エンビロン、セルコスメのメニューをご用意。<br>
        人の体がそれぞれ違うように、肌ケアも十人十色。<br>カウンセリングを元に最適なケアをご提案いたします。</p>
      <div class="menu-link">
        <%= link_to "全てのメニューを見る", inquirys_menu_path, class: "menu_link" %>
      </div>
    </div>

    <!-- お客様の声を表示 -->
    <div class="line"></div>
  <div class="questionnaire">
    <div class="title">
      <div class="title-up">questionnaires to customers</div>
      <div class="title-middle">-</div>
      <div class="title-down">【 お客様の声 】</div>
    </div>
        <div class="slider">
      <div>
        <ul>
          <li><%= image_tag "comment1.PNG" %></li>
          <li><%= image_tag "comment2.PNG" %></li>
          <li><%= image_tag "comment3.PNG" %></li>
          <li><%= image_tag "comment4.png" %></li>
        </ul>
        <span class="arrow left"></span>
        <span class="arrow right"></span>
      </div>
      <ul class="thumbs">
        <li><%= image_tag "comment1.PNG" %></li>
        <li><%= image_tag "comment2.PNG" %></li>
        <li><%= image_tag "comment3.PNG" %></li>
        <li><%= image_tag "comment4.png" %></li>
      </ul>
      </div>

    <script>
    window.addEventListener('load', function () {
      document.querySelectorAll('.slider').forEach(slider => {
        //左矢印クリック
        slider.querySelector('.left').onclick = function () {
          let ul = this.parentNode.querySelector('ul');
          ul.scrollLeft -= ul.clientWidth;
        };
        //右矢印クリック
        slider.querySelector('.right').onclick = function () {
          let ul = this.parentNode.querySelector('ul');
          ul.scrollLeft += ul.clientWidth;
        };
        //サムネイル番号のカウント用
        let thumbs_no = 0;
        //サムネイル番号の割り振りとクリックイベントの追加
        slider.querySelectorAll('.thumbs li').forEach(thumbs_elm => {
          if (thumbs_no == 0) {
            //最初は1つ目のサムネイルが選択された状態にしておく
            thumbs_elm.classList.add('selected');
          }
          //自身が何番目の要素かdataset属性に保存しておく
          thumbs_elm.dataset.no = thumbs_no++;
          //サムネイルクリック時のイベント
          thumbs_elm.onclick = function () {
            //現在アクティブなサムネイルのクラスを変更（選択解除）
            slider.querySelector('.thumbs .selected').classList.remove('selected');
            //次にアクティブにするサムネイルのクラスを変更（選択状態）
            this.classList.add('selected');
            //サムネイル番号からスクロール量を算出する
            let preview_ul = slider.querySelector('div > ul');
            preview_ul.scrollLeft = (preview_ul.clientWidth * this.dataset.no);
          }
        });
        //スクロール発生時のイベント
        slider.querySelector('div > ul').onscroll = function () {
          //onscrollはスクロールが終わるまでに何度も発生するため、
          //100ミリ秒間onscrollが発生しなかったときに限り、処理を続行する
          clearTimeout(slider.dataset.timeoutid);
          slider.dataset.timeoutid = setTimeout(function () {
            //現在アクティブなサムネイルのクラスを変更（選択解除）
            slider.querySelector('.thumbs .selected').classList.remove('selected');
            //プレビューとサムネイルのノードを取得
            let preview_ul = slider.querySelector('div > ul');
            let thumbs = slider.querySelector('.thumbs');
            //現在のスクロール量からサムネイル番号を算出
            let thumbs_no = Math.floor(preview_ul.scrollLeft / preview_ul.clientWidth);
            //アクティブにするサムネイルのクラスを変更（選択状態）
            thumbs.children[thumbs_no].classList.add('selected');
          }, 100);
        };
      });
    });
    </script>
  </div>

  <div class="line"></div>
    <!-- アクセス情報を表示 -->
    <div class="access">
        <div class="title">
          <div class="title-up">information / access</div>
          <div class="title-middle">-</div>
          <div class="title-down">【 サロン案内／アクセス 】</div>
        </div>
      <div class="access-top">
        <div class="access-flex">
          <div class="access-image">
            <%= image_tag asset_path("este_room.jpg"), class:"home" %>
          </div>
          <div class="access-information">
            <div class="access-comment">
              <div class="name">【　HEALTH & BEAUTY  TORa　】</div>
              <div class="adress">〒381-2223 長野県長野市里島27-2<br> タウンコートいずみ B102号室</div>
              <div class="phone-number">TEL 090-3408-3514</div>
              <div class="time">営業時間 10：00 〜 17：00 </div>
              完全予約制
            </div>
          </div>
        </div>
      </div>
      <div class="menu-link">
        <%= link_to "案内情報を見る", inquirys_access_path, class: "menu_link" %>
      </div>
    </div>
  </div>
  <div class="line"></div>

</div>
</body>
<%= render "shared/footer" %>

app/views/inquirys/menu.html.erb
<%= render "shared/header" %>

<div class="menu">
  <%= image_tag asset_path("este.jpeg"), class:"este-image" %>
  <div class="este-top-title">HEALTH & BEAUTY</div>


  <div class="top-menu">
    <div class="top-menu-comment">
      オイルトリートメントに精油を合わせることで、日々の心身のバランスの乱れを整えます。<br>
      静かな森の中、木漏れ日を浴びるような心地へ誘いながら、<br>
      自己治癒力を高め、内面にある健やかさと美しさを取り戻すお手伝いをさせていただきます。<br>
      大切なお身体を、日頃からトリートメントでメンテナンスすることによって不調を防ぎ、<br>
      いきいきとした素肌を保ち、軽やかな心身でお過ごしいただきたいと願っております。<br>
    </div>
  </div>

  <div class="middle-menu">
    
    <div class="kairo_menu">
      <div class="kairo_container">
        <%= image_tag"kairo_menu1.jpeg", class:"kairo_image" %>
        <div class="kairo_menu_title">【　美骨カイロコース　】<br>
          骨盤・全身調整
          <span class="kairo_sub_title">（＊ 初回(プラス30分)カウンセリングと検査が含まれます。）</span><br><br>
          肩こりや腰痛・膝痛・しびれ・神経痛の緩和、背骨や骨盤の歪みを整えて<br>
          自律神経の働きを良くしていきます。
        </div>
      </div>

      <div class="kairo_container">
        <%= image_tag"kairo_menu2.jpeg", class:"kairo_image" %>
        <div class="kairo_menu_title">【　エステコース　】<br><br>
          オイルを使った足、背中、お腹、腕、デコルテの全身オールハンドトリートメントに加え<br>
          気になる部位に集中的にアプローチ。
        </div>
      </div>
      
      <div class="kairo_container">
        <%= image_tag"kairo_menu3.jpeg", class:"kairo_image" %>
        <div class="kairo_menu_title">【　オプションコース（トリートメント）　】<br><br>
          お好みの“時間とメニュー”の組み合わせが楽しめる、当サロンの一番人気のコースです。
        </div>
      </div>

      <div class="kairo_container">
        <%= image_tag"kairo_menu4.jpeg", class:"kairo_image" %>
        <div class="kairo_menu_title">【　美肌フェイシャル　】<br><br>
          丁寧なクレンジング・洗顔の後、フェイシャルマッサージで血行を良くし、<br>
          くすみやむくみを解消します。
        </div>
      </div>

      <div class="menu-link">
        <%= link_to "詳しくメニューを見る", inquirys_menu_display_path, class: "menu_link" %>
      </div><br><br>
  </div>
</div>
<%= render "shared/footer" %>

app/views/inquirys/menu_display.html.erb
<%= render "shared/header" %>
<div class="background">
  <div class="menu_display">
    <div class="menu_display_main_title">
      <div class="menu_display_main__title">
        Menu
      </div>
      <div class="menu_display_title">美骨カイロコース</div>
      <div class="under_line"></div>
        <div class="menu_display_sub_title">骨盤・美姿勢・全身矯正（60分）
        <div class="menu_display_title_price">・・・・・・・¥ 6600</div></div>

      <div class="menu_display_title">エステコース</div>
      <div class="under_line"></div>
        <div class="menu_display_sub_title">オールハンド全身リンパトリートメント（60分）
        <div class="menu_display_title_price">・・・・¥ 7700</div></div>

      <div class="menu_display_title">オプションコース<span class="menu_display__sub_title">トリートメント</span></div> 
        <div class="under_line"></div>
        <div class="menu_display_sub_title">背中
          <div class="menu_display_title_price">・・・・・・・¥ 3300</div></div><br>
        <div class="menu_display_sub_title">お腹
          <div class="menu_display_title_price">・・・・・・・¥ 2200</div></div><br>
        <div class="menu_display_sub_title">肩・二の腕集中
          <div class="menu_display_title_price">・・・・・・・¥ 2750</div></div><br>
        <div class="menu_display_sub_title">下半身
          <div class="menu_display_title_price">・・・・・・・¥ 3300</div></div><br>
        <div class="menu_display_sub_title">デコルテ
          <div class="menu_display_title_price">・・・・・・・¥ 2200</div></div><br>
        <div class="menu_display_sub_title">ドライヘッドマッサージ
          <div class="menu_display_title_price">・・・・・・・¥ 2200</div></div><br><br>
        <div class="menu_display_sub_title">（セルライト分解クリーム使用　＋　¥ 3300）</div><br><br>
        
        <div class="menu_display_sub_title">エステコースに美骨オプション</div><br>
        <div class="menu_display_sub_title">小顔美骨調整
          <div class="menu_display_title_price">・・・・・・・¥ 3300</div></div><br>
        <div class="menu_display_sub_title">骨盤矯正
          <div class="menu_display_title_price">・・・・・・・¥ 3300</div></div><br>
      </div>
      <div class="menu_display_title">美肌フェイシャル</div>
        <div class="under_line"></div>
        <div class="menu_display_sub_title">美肌調整→ディープクレンジング→ クレイトリートメント</div><br>
        <div class="menu_display_sub_title">(フェイシャル＆デコルテ)→美容液導入→お仕上げ<br>
        <div class="menu_display_title_price">・・・・¥ 8800</div></div><br>
        <div class="menu_display_sub_title">（お肌に合わせたパック使用 + ¥ 3300）</div><br><br>
      </div>
    </div>

  </div>
</div>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, user-scalable=yes">
    <title>Tora1018</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <%= link_to image_tag( "tora_logo.JPG", class:"logo-bottom" ), "/" %>
  <p>© YN TAKIZAWA</p>
</div>

app/views/shared/_header.html.erb
<header>
  <div class='header-inner'>
      <%= link_to image_tag( 'tora_logo.JPG', size: '175x120', class:'logo' ), "/" %>
    <div id="nav-wrapper" class="nav-wrapper">
  <div class="hamburger" id="js-hamburger">
    <span class="hamburger__line hamburger__line--1"></span>
    <span class="hamburger__line hamburger__line--2"></span>
    <span class="hamburger__line hamburger__line--3"></span>
  </div>
  <nav class="sp-nav">
    <div class="menu">
      <ul>
        <li class="nac-item active">
          <%= link_to "メニュー", inquirys_menu_path, class: "nav-link" %>
        </li>
        <li class="nac-item active">
          <%= link_to "施術表/料金", inquirys_menu_display_path, class: "nav-link" %>
        </li>
        <li class="nac-item active">
          <%= link_to "ご予約", 'https://tol-app.jp/s/shgt6zy182gfq2am4m49', class: "nav-link" %>
        </li>
        <li class="nac-item active">
          <%= link_to "サロン案内/アクセス", inquirys_access_path, class: "nav-link" %>
        </li>
        
      </ul>
    </div>
  </nav>
  <div class="black-bg" id="js-black-bg"></div>
 </div>
  </div>
</header>